<!-- SPDX-License-Identifier: EPL-2.0 -->
<script setup lang="ts">
// Shown above a translated page whose English source changed after it was
// translated. `i18n-hashes.json` is generated by `docs:i18n-hashes`
// (scripts/docs-i18n-status.mjs --write-hashes) as
// `{ "<locale page relativePath>": "<English URL>" }` for stale pages only.
// The glob keeps a missing file (fresh clone, tests) from breaking the build.
import { computed } from 'vue';
import { useData, withBase } from 'vitepress';
import { pickStrings } from './strings';

const files = import.meta.glob<Record<string, string>>('../i18n-hashes.json', {
  eager: true,
  import: 'default',
});
const stale = files['../i18n-hashes.json'] ?? {};

const { lang, theme, page } = useData();
const t = computed(() => pickStrings(lang.value, theme.value.componentsByLang));
const englishUrl = computed(() => stale[page.value.relativePath]);
</script>

<template>
  <div v-if="englishUrl" class="stale-banner" role="note">
    {{ t.staleNotice }}
    <a :href="withBase(englishUrl)">{{ t.staleLink }}</a>
  </div>
</template>

<style scoped>
.stale-banner {
  margin: 0 0 20px;
  padding: 10px 14px;
  border: 1px solid var(--vp-c-warning-1);
  border-radius: 8px;
  background: var(--vp-c-warning-soft);
  font-size: 14px;
}
</style>
